[package]
name = "stentorian"
version = "0.1.0"
authors = ["Daniël Louwrink <daniel.louwrink@gmail.com>"]

[dependencies]
components = { path = "components" }
byteorder = "1.0"
bitflags = "0.8"

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
error-chain = "0.10"

log = "0.3"
