[package]
name = "rustlink"
version = "0.1.0"
authors = ["Daniël Louwrink <daniel.louwrink@gmail.com>"]

[dependencies]
components = { path = "../components" }
byteorder = "1.0.0"
bitflags = "0.8.2"

serde = "0.9.13"
serde_derive = "0.9.13"
serde_json = "0.9.10"
error-chain = "0.10.0"
